language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"

env:
    PYTHONIOENCODING=UTF-8

install:
    - pip install -r requirements.txt

script:
    - (cd lmf; python last_minute_flashcards.py --test)
